# Generated by Django 4.0.4 on 2023-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer', models.DateField(verbose_name='Primer')),
                ('ultimo', models.DateField(verbose_name='Ultimo')),
                ('detalles', models.JSONField(verbose_name='Detalles')),
            ],
        ),
    ]
