# Generated by Django 4.0.4 on 2023-09-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semana', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semana',
        ),
    ]
