# Generated by Django 4.0.4 on 2023-09-13 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semana', '0002_delete_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEvento', models.CharField(choices=[('GM', 'GUARDIA MAÑANA'), ('GT', 'GUARDIA TARDE'), ('GN', 'GUARDIA NOCHE'), ('DIS', 'DISPONIBILIDAD'), ('FRA', 'FRANCO'), ('VACA', 'VACACIONES')], max_length=4, verbose_name='Tipo de Evento')),
                ('diaInicio', models.DateField(verbose_name='Dia Inicio del Evento')),
                ('diaFin', models.DateField(verbose_name='Dia Final Evento')),
                ('horaInicio', models.TimeField(verbose_name='Hora Inicio')),
                ('duracion', models.IntegerField(choices=[(1, '7'), (2, '8'), (3, '9')], verbose_name='Duracion')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
