# Generated by Django 4.0.4 on 2023-09-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semana', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='duracion',
            field=models.IntegerField(choices=[(7, '7'), (8, '8'), (9, '9'), (4, '24')], verbose_name='Duracion'),
        ),
    ]
