# Generated by Django 4.0.4 on 2023-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semana', '0004_alter_evento_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipoEvento',
            field=models.CharField(choices=[('GUARDIA MAÑANA', 'GUARDIA MAÑANA'), ('GUARDIA TARDE', 'GUARDIA TARDE'), ('GUARDIA NOCHE', 'GUARDIA NOCHE'), ('DISPONIBILIDAD', 'DISPONIBILIDAD'), ('FRANCO', 'FRANCO'), ('VACACIONES', 'VACACIONES')], max_length=20, verbose_name='Tipo de Evento'),
        ),
    ]
