# Generated by Django 4.0.4 on 2023-10-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semana', '0005_alter_evento_tipoevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='duracion',
            field=models.IntegerField(choices=[(7, '7'), (8, '8'), (9, '9'), (24, '24')], verbose_name='Duracion'),
        ),
    ]
