# Generated by Django 4.0.4 on 2023-09-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='horaFin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hora Salida'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='horasXdia',
            field=models.IntegerField(choices=[(7, '7'), (8, '8'), (9, '9'), (4, '24')], default=1, verbose_name='Horas diarias'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='preferenciaHorario',
            field=models.IntegerField(choices=[(7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')], default=2, verbose_name='Preferencia Horario'),
        ),
    ]
