# Generated by Django 4.0.4 on 2023-10-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_usuarios_horafin_alter_usuarios_horasxdia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equiposdetrabajos',
            old_name='miembro',
            new_name='usuarios',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='horasXdia',
            field=models.IntegerField(choices=[(7, '7'), (8, '8'), (9, '9')], default=1, verbose_name='Horas diarias'),
        ),
    ]
